version: '3.8'

services:
  # Authentication service image
  authentication_service:
    build: ./AuthenticationService
    ports:
      - "8080:8080"
    depends_on:
      - mysql_authen_service
    volumes:
      - mysql-authen-data:/var/lib/mysql

  # Info service image
  info_service:
    build: ./InfoService
    ports:
      - "8081:8081"
    depends_on:
      - mysql_info_service
    volumes:
      - mysql-info-data:/var/lib/mysql

  # Course service image
  course_service:
    build: ./CourseService
    ports:
      - "8082:8082"
    depends_on:
      - mysql_course_service
    volumes:
      - mysql-course-data:/var/lib/mysql

  # Enrollment service image
  enrollment_service:
    build: ./EnrollmentService
    ports:
      - "8083:8083"
    depends_on:
      - mysql_enrollment_service
    volumes:
      - mysql-enrollment-data:/var/lib/mysql

  # Grade service image
  grade_service:
    build: ./GradeService
    ports:
      - "8084:8084"
    depends_on:
      - mysql_grade_service
    volumes:
      - mysql-grade-data:/var/lib/mysql

  # Payment service image
  payment_service:
    build: ./PaymentService
    ports:
      - "8085:8085"
    depends_on:
      - mysql_payment_service
    volumes:
      - mysql-payment-data:/var/lib/mysql

  # Api Gateway image
  api_gateway:
    build: ./ApiGatewayService
    ports:
      - "8000:8000"
    depends_on:
      - redis # Thêm service Redis vào dependencies của API Gateway
    environment:
      REDIS_HOST: redis # Sử dụng tên service của Redis
      REDIS_PORT: 6379

  redis:
    image: "redis:3.2.12"
    ports:
      - "6379:6379"

  # MySQL for authentication
  mysql_authen_service:
    image: mysql:8.0
    container_name: mysql_authen_service
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: authentication_service
    ports:
      - "3307:3306"
    volumes:
      - mysql-authen-data:/var/lib/mysql

  # MySQL for info service
  mysql_info_service:
    image: mysql:8.0
    container_name: mysql_info_service
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: info_service
    ports:
      - "3311:3306"
    volumes:
      - mysql-info-data:/var/lib/mysql

  # MySQL for course service
  mysql_course_service:
    image: mysql:8.0
    container_name: mysql_course_service
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: course_service
    ports:
      - "3308:3306"
    volumes:
      - mysql-course-data:/var/lib/mysql

  # MySQL for enrollment service
  mysql_enrollment_service:
    image: mysql:8.0
    container_name: mysql_enrollment_service
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: enrollment_service
    ports:
      - "3309:3306"
    volumes:
      - mysql-enrollment-data:/var/lib/mysql

  # MySQL grade service
  mysql_grade_service:
    image: mysql:8.0
    container_name: mysql_grade_service
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: grade_service
    ports:
      - "3310:3306"
    volumes:
      - mysql-grade-data:/var/lib/mysql

  # MySQL for payment service
  mysql_payment_service:
    image: mysql:8.0
    container_name: mysql_payment_service
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: payment_service
    ports:
      - "3312:3306"
    volumes:
      - mysql-payment-data:/var/lib/mysql

volumes:
  mysql-authen-data:
  mysql-info-data:
  mysql-course-data:
  mysql-enrollment-data:
  mysql-grade-data:
  mysql-payment-data:
