version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_authen_service
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: authentication_service
    ports:
      - "3307:3306" # Change external port to 3307 to avoid conflicts
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
    container_name: backend_authen_service
    environment:
      NODE_ENV: development
      PORT: 8080
      BACKEND_URL: http://localhost:8080
      DATABASE_NAME: authentication_service
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: mysql
      DIALECT: mysql
      DATABASE_PORT: 3306 # Internal port for MySQL container
      EXPIRESD_IN: 2700
      MAX_AGE: 4000
      SECRET_KEY: 123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
