name: Push Request Actions

on:
  push:
    branches:
      - main
    path:
      - ApiGatewayService/**
  workflow_dispatch:

jobs:
  push-request:
    runs-on: ubuntu-latest

    #Setting the direction to execute actions
    defaults:
      run:
        working-directory: ApiGatewayService

    steps:
      - uses: actions/checkout@v2

      # Setup NodeJS
      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Compile the code
      - name: Build project
        run: npm run build --if-present

      # Install libraries
      - name: Install libraries
        run: npm install

      # Config git user
      - run: git config user.email "tranlehuy0407@gmail.com"
      - run: git config user.name "@github-ci"

      # Update version
      - name: Version app
        run: npm version patch

      # Pulling project
      - name: Pull project
        run: git pull

      # Repush to github
      - run: git push
      - run: git push --follow-tags